### ISSUE TITLE
How to improve performance

### ISSUE THREAD

**Issue by efaulhaber** [trixi-framework/TrixiParticles.jl#37]
This issue is to discuss options to improve single-processor performance (multithreaded, but no MPI yet).

The plan so far:

- [x] Solve #29 and resolve all type instabilities (solved in #36).
- [x] Investigate if `thread=OrdinaryDiffEq.True()` can improve performance of the time integration method once https://github.com/JuliaSIMD/StrideArrays.jl/issues/62 is resolved. Edit: We are now using `ThreadedBroadcastArray`s for this.
- [x] Further optimize PK1 computation for structure dynamics (solved in #38).
- [ ] Use symmetry of interactions? We could skip half of the fluid-fluid interaction by applying the same force with a flipped sign to the neighbor particle. However, some SPH codes don't do this because it makes the computations and memory accesses less optimal, especially on GPUs. We could also skip the solid-fluid interaction by using symmetry in the fluid-solid interaction.
- [x] A single `@threaded` loop over all particles, which then includes all fluid-* interactions could potentially improve performance. Edit: Benchmarked in #1082. Didn't make a difference for large enough problems.
- [x] Improve neighborhood search update. The NHS update is a bottleneck on multiple threads because the implementation does not use multithreading (#65).
- [x] Rework the neighborhood search. We might be able to get a significant speedup for large simulations by using a contiguous memory layout. Edit: Benchmarked in trixi-framework/PointNeighbors.jl#120
