### ISSUE TITLE
Testing Master Plan

### ISSUE THREAD

**Issue by efaulhaber** [trixi-framework/TrixiParticles.jl#48]
This is a to-do list for testing and to keep track of the tests we already have.
- General unit tests
  - [x] Unit tests for constructors and `show`
  - [ ] `summation_density!` (we only have a very simple test with a single particle, yet)
  - [ ] Corrections
  - [ ] `restart_with!` (WCSPH + TLSPH)
  - `InitialCondition`
    - [x] `union`
    - [x] `setdiff`
    - [x] `intersect`
  - Setups
    - [x] `RectangularShape`
    - [x] `RectangularTank`
    - [x] `SphereShape`
  - Smoothing kernels
    - [x] Integral equals 1 (#237)
    - [ ] Find more useful tests for kernels
    - [x] Test derivatives against automatic differentiation (#290)
- Unit tests for WCSPH RHS
  - [x] State equations (#292)
  - [ ] Viscosity
  - [x] `pressure_acceleration` (#293)
  - [ ] `continuity_equation!`
  - `interact!`
    - [x] Linear and angular momentum conservation (#293)
    - [x] Total energy conservation (#294)
    - [ ] Momentum and energy conservation with viscosity
    - [ ] Momentum and energy conservation with density diffusion
    - [ ] More tests?
  - [ ] Density diffusion terms
- Unit tests for boundary system RHS
  - [ ] Monaghan-Kajtar kernel
  - [ ] Monaghan-Kajtar `pressure_acceleration`
  - [x] Dummy particles `pressure_acceleration` (#327)
  - [ ] Adami pressure extrapolation
  - [ ] `interact!`
- Unit tests for EDAC RHS
  - [ ] `pressure_evolution`
  - [ ]  `interact!`
- Unit tests for solid dynamics
  - [ ] Penalty force
  - [ ] Correction matrix
  - [x] Deformation gradient and stress tensor
- Unit tests for neighborhood search
  - [x] `TrivialNeighborhoodSearch`
  - `GridNeighborhoodSearch`
    - [x] Basic 2D
    - [x] Basic 3D
    - [x] Periodicity 2D
    - [x] Periodicity 3D
- [ ] Linear interpolation
- [ ] Tests for visualization. Especially verification of plots (see #629).
- [ ] Tests for callbacks
- Example tests
  - [x] Simple smoke tests as system tests (#47)
  - [ ] Add some kind of solution verification for system tests. At least to catch obvious problems like when the solid in FSI is not moving.
  - [ ] Properly verify examples that are reproducing papers against the papers.
  - [ ] Run example tests with coverage (expensive). We have to track this coverage separately from the unit test coverage, or the unit test coverage report is useless. We may want to think about showing only the unit test coverage badge, or both if possible. Otherwise, the example coverage should just be used internally to keep track of the example tests.
  - [ ] Try to test the full feature set with system tests (run examples with different BCs, with and without NHS, with and without viscosity, etc.)
- [x] Add coverage for unit tests (#72)
- [x] Doctests
- [x] Run CI on LTS and current stable release versions of Julia (expensive).
