### ISSUE TITLE
Road to TrixiParticles.jk on GPUs

### ISSUE THREAD

**Issue by efaulhaber** [trixi-framework/TrixiParticles.jl#484]
- [ ] Make array types in structs generic. Change types like `Array{ELTYPE, 2}` to type parameters (Proof of Concept in #474).
- [ ] Recursively convert (adapt) `Semidiscretization` object to GPU types with Adapt.jl (PoC in #474).
- [ ] Minimally invasive working GPU implementation with KernelAbstractions.jl and CUDA backend without neighborhood search (PoC in #474).
- [ ] As above, but with AMD backend.
- [ ] First memory-hungry GPU-compatible grid neighborhood search, allocating the full grid as one big array (PoC in #483).
- [ ] Memory-efficient GPU-compatible grid neighborhood search.
- [ ] Benchmark, profile and optimize interactions on GPUs.

**Comment by efaulhaber** [comment]
Here are some remaining To-Dos from #723:
- [ ] The `SchoenbergQuarticSplineKernel` does not work on GPUs (https://github.com/JuliaGPU/CUDA.jl/issues/2681 and https://github.com/JuliaGPU/Metal.jl/issues/550).
- [ ] Some weird Heisenbug breaking the 3D dam break on Metal (https://github.com/JuliaGPU/Metal.jl/issues/549). But only on my machine, apparently.
- [ ] The open boundary system is not GPU-compatible (https://github.com/trixi-framework/PointNeighbors.jl/issues/20).
- [ ] Monaghan-Kajtar BC don't work with `Float32` (https://github.com/JuliaGPU/Metal.jl/issues/552).
- [ ] Intel GPUs just report a segfault in the first example (https://buildkite.com/julialang/trixiparticles/builds/121#01956711-2f9f-45c6-a3ce-b591179eac07).
