### ISSUE TITLE
Fix `BoundaryModelDummyParticles()` for FSI

### ISSUE THREAD

**Issue by LasNikas** [trixi-framework/TrixiParticles.jl#53]
- [x]  Incorrect placement of boundary wall for multiple layers (solved in #42)
- [x]  `continuity_equation!()` dispatched with `SummationDensity`  is needed for the solid-fluid interaction as well. ( #59  )
- [x] Differentiate movement function for moving boundaries (#101)
- [ ] provide solid particle acceleration for `AdamiPressureExtrapolation` (#262)
- [x] Interaction between different particle spacing (#59 )
- [x] update solid container in `update3!()` (#59 )
- [x] hydrodynamic mass for solid particles (#59 )
